# Generated by Django 4.2.5 on 2024-03-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_mymodel_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='category',
            field=models.TextField(default='channel_post'),
        ),
    ]
