# Generated by Django 4.2.5 on 2024-03-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_mymodel_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='parser_site',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('project', models.TextField()),
                ('type', models.TextField()),
                ('use_proxy', models.BooleanField(default=False)),
            ],
        ),
    ]
