# Generated by Django 4.2.5 on 2024-03-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_mymodel_category'),
        ('panel', '0003_parser_site'),
    ]

    operations = [
    ]
