# Generated by Django 4.2.5 on 2023-10-18 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chat_id', models.TextField(default='')),
                ('text', models.TextField()),
                ('source', models.TextField()),
                ('time_stringify', models.TextField(default='')),
                ('photo', models.TextField(default='')),
                ('data', models.TextField(default='')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.TextField(default='')),
                ('account', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
