# Generated by Django 4.2.5 on 2023-11-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdatabase_comment_alter_useraccount_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='favourites',
            field=models.TextField(default=''),
        ),
    ]
